# Generated by Django 2.0 on 2017-12-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(help_text='Entrar com a chave', max_length=13)),
                ('nome', models.CharField(help_text='Entrar com nome', max_length=200)),
                ('decricao', models.TextField(help_text='Entrar com descricao')),
            ],
        ),
    ]
