# Generated by Django 2.0 on 2017-12-29 20:15

from django.db import migrations
from django.conf import settings

def create_data(apps, schema_editor):
    Produto = apps.get_model('catalogo', 'Produto')
    User = apps.get_model(settings.AUTH_USER_MODEL)

    user = User(pk=1, username="auth0user", is_active=True , email="junio.salome@gmail.com")
    user.save()

    Produto(chave='chave1',name='Produto 1', description='Produto 1').save()
    Produto(chave='chave2',name='Produto 2', description='Produto 2').save()
    Produto(chave='chave3',name='Produto 3', description='Produto 3').save()


    
class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
